language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
dist: trusty
sudo: required
addons:
  chrome: stable
install:
  - yarn install --ignore-engines
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
